export const disabled: string;
export const navigation: string;
export const next: string;
export const pageLink: string;
export const pageLinks: string;
export const pageSkip: string;
export const pagination: string;
export const previous: string;
export const status: string;
